<script setup>
/* eslint-disable vue/no-bare-strings-in-template */
import { computed, onMounted, ref } from 'vue';
import { useRoute, useRouter } from 'vue-router';
import { salesOrdersAPI } from 'dashboard/api/crm/commercialCycle';
import { useAlert } from 'dashboard/composables';
const route=useRoute(); const router=useRouter();
const rows=ref([]); const loading=ref(false); const selected=ref(null); const saving=ref(false);
const money=v=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format((Number(v)||0)/100);
const totals=computed(()=>({count:rows.value.length,total:rows.value.reduce((s,r)=>s+(Number(r.total_cents)||0),0),pending:rows.value.filter(r=>['pending','approved','separating','invoiced','shipped'].includes(r.status)).length,completed:rows.value.filter(r=>['completed'].includes(r.status)).length}));
const paymentLabel=r=>r.payment_condition==='cash'?'À vista':r.payment_condition==='down_payment_installments'?'Entrada + parcelas':r.payment_condition==='installments'?'Parcelado':'A definir';
const load=async()=>{loading.value=true;try{const r=await salesOrdersAPI.list();rows.value=r.data||[]; const q=route.query.orderId; if(q) selected.value=rows.value.find(x=>String(x.id)===String(q))||null;}finally{loading.value=false;}};
const open=row=>{selected.value=row;router.replace({query:{...route.query,orderId:row.id}})};
const close=()=>{selected.value=null;const q={...route.query};delete q.orderId;router.replace({query:q});};
const changeStatus=async status=>{if(!selected.value)return;saving.value=true;try{const {data}=await salesOrdersAPI.update(selected.value.id,{sales_order:{status}});selected.value=data;await load();useAlert('Status do pedido atualizado.');}catch(e){useAlert(e.response?.data?.errors?.join(', ')||'Não foi possível atualizar o pedido.');}finally{saving.value=false;}};
onMounted(load);
</script>
<template>
<div class="h-full overflow-auto bg-n-surface-1 p-4 sm:p-6">
  <header class="mb-5 flex items-center gap-3"><span class="grid size-11 place-content-center rounded-2xl bg-emerald-50 text-emerald-700"><i class="i-lucide-shopping-cart size-5" /></span><div><h2 class="text-2xl font-bold text-n-slate-12">Pedidos / Vendas</h2><p class="text-sm text-n-slate-9">Ciclo comercial gerado a partir das propostas aceitas.</p></div></header>
  <section class="mb-4 grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><article class="rounded-2xl border border-n-weak bg-white p-4"><p class="text-xs text-n-slate-9">Pedidos</p><strong class="mt-1 block text-2xl">{{ totals.count }}</strong></article><article class="rounded-2xl border border-n-weak bg-white p-4"><p class="text-xs text-n-slate-9">Valor vendido</p><strong class="mt-1 block text-xl text-emerald-700">{{ money(totals.total) }}</strong></article><article class="rounded-2xl border border-n-weak bg-white p-4"><p class="text-xs text-n-slate-9">Em andamento</p><strong class="mt-1 block text-2xl">{{ totals.pending }}</strong></article><article class="rounded-2xl border border-n-weak bg-white p-4"><p class="text-xs text-n-slate-9">Concluídos / ativos</p><strong class="mt-1 block text-2xl">{{ totals.completed }}</strong></article></section>
  <div class="overflow-hidden rounded-2xl border border-n-weak bg-white shadow-sm"><table class="w-full table-fixed text-sm"><thead class="bg-n-alpha-2 text-left text-xs uppercase text-n-slate-9"><tr><th class="w-[28%] p-3">Pedido / Cliente</th><th class="w-[24%] p-3">Origem</th><th class="w-[16%] p-3">Pagamento</th><th class="w-[14%] p-3">Valor</th><th class="w-[12%] p-3">Status</th><th class="w-[6%] p-3"></th></tr></thead><tbody class="divide-y divide-n-weak"><tr v-if="loading"><td colspan="6" class="p-10 text-center">Carregando…</td></tr><tr v-for="row in rows" :key="row.id" class="cursor-pointer hover:bg-n-alpha-2" @click="open(row)"><td class="p-3"><strong>{{ row.order_number || `#${row.id}` }}</strong><p class="text-xs text-n-slate-9">{{ row.contact?.name || 'Cliente não informado' }}</p></td><td class="p-3"><span>{{ row.deal?.title || '—' }}</span><p class="text-xs text-n-slate-9">{{ row.proposal?.proposal_number || 'Sem proposta' }}</p></td><td class="p-3">{{ paymentLabel(row) }}<p class="text-xs text-n-slate-9">{{ row.payment_method || 'A definir' }}</p></td><td class="p-3 font-semibold">{{ money(row.total_cents) }}</td><td class="p-3"><span class="rounded-full bg-emerald-50 px-2 py-1 text-xs font-semibold text-emerald-700">{{ row.status }}</span></td><td class="p-3 text-right"><i class="i-lucide-chevron-right" /></td></tr><tr v-if="!loading&&!rows.length"><td colspan="6" class="p-10 text-center text-n-slate-9">Nenhum pedido ainda. Aceite uma proposta e use “Converter em pedido”.</td></tr></tbody></table></div>
  <Teleport to="body"><div v-if="selected" class="fixed inset-0 z-[90] flex justify-end bg-black/40" @click.self="close"><aside class="h-full w-full max-w-xl overflow-auto bg-white p-6 shadow-2xl"><div class="flex justify-between"><div><p class="text-xs uppercase text-n-slate-9">Pedido / Venda</p><h3 class="text-xl font-bold">{{ selected.order_number }}</h3><p class="text-sm text-n-slate-9">{{ selected.contact?.name }}</p></div><button class="i-lucide-x size-5" @click="close" /></div><div class="mt-6 grid grid-cols-2 gap-3 rounded-xl border border-n-weak p-4 text-sm"><div><span class="text-xs text-n-slate-9">Total</span><strong class="block text-lg">{{ money(selected.total_cents) }}</strong></div><div><span class="text-xs text-n-slate-9">Produtos</span><strong class="block">{{ money(selected.products_cents) }}</strong></div><div><span class="text-xs text-n-slate-9">Frete</span><strong class="block">{{ money(selected.shipping_cents) }}</strong></div><div><span class="text-xs text-n-slate-9">Mensalidade</span><strong class="block">{{ selected.monthly_cents ? `${money(selected.monthly_cents)}/mês` : 'Sem mensalidade' }}</strong></div></div><section class="mt-4 rounded-xl border border-n-weak p-4"><h4 class="font-semibold">Condição de pagamento</h4><p class="mt-2 text-sm">{{ paymentLabel(selected) }} · {{ selected.payment_method || 'forma a definir' }}</p><p v-if="selected.down_payment_cents" class="mt-1 text-sm">Entrada: {{ money(selected.down_payment_cents) }}</p><p v-if="selected.installments_count>1" class="mt-1 text-sm">Parcelas: {{ selected.installments_count }}</p></section><section class="mt-4 rounded-xl border border-n-weak p-4"><label class="text-sm font-semibold">Status<select :value="selected.status" :disabled="saving" class="mt-2 w-full rounded-lg border border-n-weak px-3 py-2" @change="changeStatus($event.target.value)"><option value="pending">Pendente</option><option value="approved">Aprovado</option><option value="separating">Em separação</option><option value="invoiced">Faturado</option><option value="shipped">Enviado</option><option value="completed">Concluído</option><option value="canceled">Cancelado</option></select></label></section></aside></div></Teleport>
</div>
</template>
